services:
  backend:
    image: ${BACKEND_IMAGE_NAME}
    env_file: .env
    volumes:
      - db_data:/app/data
    restart: unless-stopped

  frontend:
    image: ${FRONTEND_IMAGE_NAME}
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
